esphome:
  name: influxdb-full
  friendly_name: Full InfluxDB Example

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  hardware_uart: USB_SERIAL_JTAG

wifi:
  id: _wifi
  networks:
    - ssid: example-network
      password: network-password

api:

external_components:
  - source: github://kpfleming/esphome-influxdb_v2_oss

time:
  - id: _time
    platform: homeassistant
    timezone: EST5EDT,M3.2.0,M11.1.0

uart:
  - id: senseair_s8_uart
    rx_pin: GPIO0
    tx_pin: GPIO1
    baud_rate: 9600

  - id: pms5003_uart
    rx_pin: GPIO20
    tx_pin: GPIO21
    baud_rate: 9600

i2c:
  sda: GPIO7
  scl: GPIO6
  frequency: 400kHz

binary_sensor:
  - id: _wifi_connected
    platform: template
    lambda: |-
      return id(_wifi).is_connected();

sensor:
  - id: _uptime
    platform: uptime
    name: ${node_name} Uptime

  - id: _wifi_rssi
    platform: wifi_signal
    name: ${node_name} WiFi Signal

  - platform: pmsx003
    type: PMSX003
    uart_id: pms5003_uart
    update_interval: 2min
    pm_0_3um:
      id: pm_0_3um
      name: ${node_friendly_name} PM 0.3
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    pm_1_0:
      id: pm_1_0
      name: ${node_friendly_name} PM 1.0
      device_class: pm1
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    pm_2_5:
      id: pm_2_5
      name: ${node_friendly_name} PM 2.5
      device_class: pm25
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    pm_10_0:
      id: pm_10_0
      name: ${node_friendly_name} PM 10.0
      device_class: pm10
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30

  - platform: senseair
    uart_id: senseair_s8_uart
    update_interval: 2min
    co2:
      id: co2
      name: ${node_friendly_name} CO2
      filters:
        - skip_initial: 2
        - clamp:
            min_value: 400
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30

  - platform: sht4x
    address: 0x44
    update_interval: 2min
    temperature:
      id: temperature_c
      name: ${node_friendly_name} Temperature
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30

  - id: temperature_f
    platform: copy
    source_id: temperature_c
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    filters:
      - multiply: 1.8
      - offset: 32.0

text_sensor:
  - platform: wifi_info
    ip_address:
      id: _wifi_ip_address

http_request:
  useragent: esphome/influxdb
  timeout: 15s
  watchdog_timeout: 15s

influxdb_v2_oss:
  url: http://influxdb.example.com:8086
  organization: example
  token: influxdb-token
  time_id: _time
  backlog_max_depth: 60
  backlog_drain_batch: 10
  bucket: iot_devices
  measurement: info
  tags:
    device: ${node_name}
  sensors:
    _uptime:
      name: uptime
    _wifi_rssi:
      name: rssi
    _wifi_connected:
      name: connected
    _wifi_ip_address:
      name: ip_address

    pm_0_3um:
      #bucket: air_quality
      measurement: particulate_matter
    pm_1_0:
      #bucket: air_quality
      measurement: particulate_matter
    pm_2_5:
      #bucket: air_quality
      measurement: particulate_matter
    pm_10_0:
      #bucket: air_quality
      measurement: particulate_matter

    co2:
      #bucket: air_quality
      measurement: carbon_dioxide

    temperature_c:
      name: temperature
      #bucket: air_quality
      measurement: temperature
      tags:
        scale: C

    temperature_f:
      name: temperature
      #bucket: air_quality
      tags:
        scale: F
