esphome:
  name: influxdb-minimal
  friendly_name: Minimal InfluxDB Example

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  networks:
    - ssid: example-network
      password: network-password

api:

external_components:
  - source: github://kpfleming/esphome-influxdb_v2_oss

time:
  - id: _time
    platform: homeassistant
    timezone: EST5EDT,M3.2.0,M11.1.0

sensor:
  - platform: uptime
    name: Uptime
    accuracy_decimals: 2

  - platform: wifi_signal
    name: WiFi Signal
    accuracy_decimals: 1

http_request:
  useragent: esphome/influxdb
  timeout: 15s
  watchdog_timeout: 15s

influxdb_v2_oss:
  url: http://influxdb.example.com:8086
  organization: example
  token: influxdb-token
  time_id: _time
  backlog_max_depth: 60
  backlog_drain_batch: 10
  tags:
    device: ${node_name}
